# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# development:
#   adapter: mysql2
#   host: localhost
#   encoding: utf8
#   database: newkprf
#   user: root
#   password: rjvbccfh

production:
  adapter: mysql2
  host: localhost
  encoding: utf8
  database: kprf
  user: root
  password: kprf-arh